Simplify getting started doc for easy start
CiscoCloud/vaquero-docs pull request #109
Opened 2017-10-27 22:37 UTC by fattarsi

Collaborative effort with @abemusic and @yakbulut

2017-10-30 13:22 UTC, abemusic requested changes

2017-10-30 13:22 UTC, abemusic commented on docs/current/getting-started.md
> +At this point, you've successfully run Vaquero and provisioned a CentOS machine using VMs in your local environment. In "standalone mode", the Vaquero server and agent run together in a single VM (vs
> It's also possible to run them in separate VMs, which can demonstrate how Vaquero can be used to manage agents running in different locations.

If we're going to jump into baremetal, I'd probably just take the quoted bit out or rephrase it in a way that's clear that baremetal is production and VMs is not.

2017-10-31 13:22 UTC, abemusic approved these changes
LGTM

2017-10-31 13:23 UTC, abemusic approved these changes

2017-10-31 13:24 UTC, abemusic commented
@jmeridth looks like the recently toggled "review required" is not accepting my review. Probably because I don't have write access?

2017-10-31 16:40 UTC, jmeridth approved these changes

2017-10-31 16:40 UTC, merged