Removing DHCPCIDR docs
CiscoCloud/vaquero-docs pull request #40
Opened 2016-10-11 17:18 UTC by stephenrlouie

2016-10-12 16:47 UTC, mikeynap requested changes
Proposed Documentation Changes.

2016-10-12 16:47 UTC, mikeynap commented on docs/current/README.md
> +DHCP:
Not exactly. Change this to JUST be 
- DHCPMode: 
(i.e. revert to the old version, but remove DHCPCIDR). See https://github.com/CiscoCloud/vaquero/issues/333 for further clarification.

2016-10-12 16:47 UTC, mikeynap commented on docs/current/README.md
> +- DHCP: One of two modes, `proxy` or `server`. DHCP endpoint address. Leaving the DHCP fields empty will disable all DHCP vaquero functionality.
DHCPMode: `proxy`, `server` or `none` (maybe off?).  Leaving the DHCPMode field empty will disable all DHCP vaquero functionality.  

DHCPMode: Proxy enables ProxyDHCP. ProxyDHCP works with an existing DHCP Server to provide PXEBoot functionality, while leaving the managing and assigning of IP addresses to the other DHCP Server. ONLY enable this if you already have a DHCP server with entries for all the hosts in your Data Model.

DHCPMode: server runs vaquero as a DHCP server.  Vaquero does not manage free address pools or leases; it simply assigns based of the static configuration defined in the data model.

2016-10-12 16:47 UTC, mikeynap commented on docs/current/README.md
> +- DHCP: One of two modes, `proxy` or `server`. DHCP endpoint address. Leaving the DHCP fields empty will disable all DHCP vaquero functionality.
*Something along those lines.

2016-10-17 19:59 UTC, stephenrlouie commented
@mikeynap fixed

2016-10-17 21:50 UTC, merged